name: Build and Push Docker Container PRD

on:
  workflow_dispatch:
    inputs:
      jmx_exporter_version:
        description: 'JMX Exporter Version'
        required: false
        default: '1.4.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Read version from jmx_exporter_version.txt
        id: version
        run: echo "JMX_EXPORTER_VERSION=$(cat jmx_exporter_version.txt)" >> $GITHUB_ENV

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions/checkout@v5
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
              
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=sha
            type=raw,value=jmx_exporter-${{ env.JMX_EXPORTER_VERSION }}
            type=raw,value=${{ github.repository.tag_name }}

      -   name: Build and push Docker images
          id: push
          uses: docker/build-push-action@v6
          with:
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              JMX_EXPORTER_VERSION=${{ env.JMX_EXPORTER_VERSION }}
            platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
            outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Prometheus jmx-exporter https://prometheus.github.io/jmx_exporter/${{ env.JMX_EXPORTER_VERSION }}/,annotation-index.org.opencontainers.image.version=${{ env.JMX_EXPORTER_VERSION }}
